# == mkdocs config ==

# == project information ==
site_name: Seaside - Python
site_url: https://seaside.hammad.fun
site_author: Hammad Saeed
site_description: A ***super comfy*** & ***foundational*** python toolkit for using *LLM's* & building *AI agents* & *multi agent workflows*.

# == repository information ==
repo_name: hsaeed3/seaside
repo_url: https://github.com/hsaeed3/seaside

# == theme configuration ==
theme:

  # == name / core config ==
  name: material

  # == theme config ==
  palette:
    # == dark theme (default)
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    # == light theme
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: "#f5f5f0"  # soft off-white
      accent: "#e6e6dc"   # warm beige
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode

  # == mkdocs feature config ==
  features:
    # == announcement plugins (notifications)
    - announce.dismiss
    # == content plugins (page blocks / code blocks)
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    # == header plugins
    # - header.autohide
    - header.sticky
    # == navigation plugins
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    # == search plugins
    - search.highlight
    - search.share
    - search.suggest
    # == table of contents plugins
    - toc.integrate
    - toc.follow

# == extras config ==
extra_css:
  - stylesheets/extras.css
extra_javascript:
  - stylesheets/extras.js